inputs:
  registry-url:
    description: The registry url for publishing.
runs:
  using: "composite"
  steps:
    - run: |
        npm install -g corepack@latest
        corepack enable
      shell: bash
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: "pnpm"
        cache-dependency-path: ./pnpm-lock.yaml
        registry-url: ${{ inputs.registry-url }}
    - run: pnpm install
      shell: bash
