runs:
  using: "composite"
  steps:
    - run: corepack enable
      shell: bash
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: "pnpm"
        cache-dependency-path: ./pnpm-lock.yaml
    - run: pnpm install
      shell: bash
